name: DevDeploy
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
            node-version: 18.x
      - run: npm i
      - run: npm run build
      - run: npm run test
      
      - if: ${{ github.event_name == 'push' && success() }}
        name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with: 
          personal_token: ${{ secrets.GIT_TOKEN }} # 令牌
          publish_dir: ./dist # 构建后的文件目录
          external_repository: JunLiangWangX/BootsJS # 仓库B，格式为：user/repo
          publish_branch: dist # 仓库B的分支
